config/routes.rb
Rails.application.routes.draw do

  get 'items/create'

  get 'items/show'

  get 'users/show'

  get 'welcome/index'

  get 'welcome/about'

  root 'users#show'

  devise_for :users

  resources :users, only: [:show] do #only show items to their owners.
    resources :items, only: [:create, :destroy]
  end

end

app/models/item.rb
class Item < ActiveRecord::Base
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :items
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController

  def create
    @user = User.find(params[:user_id])
    # current_user === @user any way, so no need to do current_user = @user ?
    @item = current_user.items.create(item_params)

    # or
    #@item = Item.new(item_params)
    #@item.user = current_user    but need to redirect_to @item.user

    if @item.save
      flash[:notice] = 'Just created a new Item!'
      redirect_to @user
    else
      flash[:notice] = 'Failed to create the Item!'
      redirect_to @user
    end
  end

  def show
  end

  def destroy
    @user = User.find(params[:user_id])
    @item = Item.find(params[:id]) #not params[:item_id]
    @item.destroy

    if @item.destroy
      flash[:notice] = 'Item was checked! Will be deleted after 7 days!'
      redirect_to @user
    else
      flash[:notice] = 'Alert! Unable to delete the item!'
      redirect_to @user
    end
  end

  private
  def item_params
    params.require(:item).permit(:name)
  end

  respond_to do |format|
    format.html
    format.js
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id] || current_user.id)
    @items = @user.items
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  before_action :authenticate_user!, except: [:index, :about]

  def index
  end

  def about
  end

  respond_to do |format|
    format.html
    format.js
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/items/_form.html.erb
<%= form_for [user, user.items.new] do |f| %>
  <div class='form-group'>
    <%= f.label :Item %>
    <%= f.text_field :name, class: 'form_control', placeholder: 'Enter your new item:' %>
  </div>
  <div class="form-group">
    <%= f.submit 'Save', class: 'btn btn-success' %>
  </div>
<% end %>

app/views/items/_item.html.erb
<div class="list-group">
    <%= link_to "", user_item_path(@user.id, item.id), method: :delete, class: 'glyphicon glyphicon-check' %>
    <%= item.name%> -
    <small>submitted <%= time_ago_in_words(item.created_at) %> ago |
          Time left: about <%= distance_of_time_in_words(Time.now, item.created_at + 7.days) %></small>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TodolistBE</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

  <!--
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= stylesheet_link_tag    "application", media: "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
  -->
</head>
<body>
  <div class="pull-right">
    <% if user_signed_in? %>
      Signed in as: <strong><%= current_user.email %></strong> <br />
      Edit <%= link_to current_user.email, edit_user_registration_path, :class => 'navbar-link' %>
      <br>
      <%= link_to "Item List", user_path(current_user) %>
      <br>
      <%= link_to "Sign Out", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
    <% else %>
      <%= link_to "Sign Up", new_user_registration_path, :class => 'navbar-link' %> -
      <%= link_to "Sign In", new_user_session_path, :class => 'navbar-link'  %>
    <% end %>
  </div>

  <div>
    <%= image_tag("work desk 1 copy.jpg", width: '1130px') %>
  </div>
  <div class="pull-center">
    <ul class="nav nav-tabs">
      <li><%= link_to "Home", welcome_index_path %></li>
      <li><%= link_to "About", welcome_about_path %></li>
    </ul>
  </div>
<%= yield %>

</body>
</html>

app/views/users/show.html.erb
<h3 class = 'media-heading'>Hello: <%= @user.email %></h3>
You have <%= pluralize(@user.items.count, 'items') %> listed


<%= render @items %>

<h4>Make new list! </h4><br>
<%= render partial: 'items/form', locals: {user: @user} %>

app/views/welcome/about.html.erb
<h1>About To Do List</h1>

<h3>It is a self-destructing app which automatically deletes tasks after 7 days.</h3>
<h3>It keeps your life much more focused on and free of clutter!</h3>
<h3>It is designed to improve your productivity, say more then 0% by statistics. Give it try!!!</h3>

app/views/welcome/index.html.erb
<div class="jumbotron text-center">
  <div class="text-vertical-center">
    <h1>To Do List</h1>
      <h3>To Do List is a self-destructing app which automatically deletes tasks from the list if you have not done them in 7 days.</h3>
      <h3>It keeps your life much more focused on <em>To-Do-List</em> and free of clutter!</h3>
    <br>

  </div>